name: Build iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          sandbox = false
          
    - name: Build ipa
      run: |
        cd ios-port
        nix build .#default
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenToonz-iOS
        path: ios-port/result/OpenToonz.ipa

    - name: Create Release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest-ios-build
        name: Latest iOS Build
        draft: false
        prerelease: true
        files: ios-port/result/OpenToonz.ipa
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
